---
AWSTemplateFormatVersion: '2010-09-09'

Description: Custom CFN Certificate Provider with DNS validation support

Parameters:
  S3BucketName:
    Type: String
    Default: ''
  S3BucketPrefix:
    Type: String
    Default: 'binxio-public'
  CFNCustomProviderZipFileName:
    Type: String
    Default: 'lambdas/cfn-certificate-provider-0.2.4.zip'

Conditions:
  UseBucketName: !Not [!Equals [!Ref S3BucketName, ""]]

Resources:
  CFNCustomProviderLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - CFNCustomProvider
    Properties:
      LogGroupName: !Sub /aws/lambda/${CFNCustomProvider}
      RetentionInDays: 7
  CFNCustomProvider:
    Type: AWS::Lambda::Function
    Properties:
      Description: CFN Certificate Domain Resource Record Provider
      Code:
        S3Bucket: !If [UseBucketName, !Ref S3BucketName, !Sub '${S3BucketPrefix}-${AWS::Region}']
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      FunctionName: binxio-cfn-certificate-provider
      Handler: provider.handler
      MemorySize: 128
      Role: arn:aws:iam::630337661278:role/lambda-dynamo
      Runtime: python3.6
      Timeout: 300